global_label palettePETIcon
    .incbin "images/pet/pet.gbapal"

global_label tilesetPETIcon
    .incbin "images/pet/pet.4bpp"

global_label tilesetAlert0
    .incbin "images/pet/alert/0.4bpp"
global_label tilesetAlert1
    .incbin "images/pet/alert/1.4bpp"
global_label tilesetAlert2
    .incbin "images/pet/alert/2.4bpp"
global_label tilesetAlert3
    .incbin "images/pet/alert/3.4bpp"
global_label tilesetAlert4
    .incbin "images/pet/alert/4.4bpp"
global_label tilesetAlert5
    .incbin "images/pet/alert/5.4bpp"
